### PR TITLE
added some methods to support generation from a given template.

### PR DESCRIPTION
**Pull request by mahakaal**

### CODE REVIEW

**Comment by mahakaal** [comment]
merge

**Comment by bobvandevijver** [comment]
I'm not sure why you would want to add these functions in this form. Maybe the suggestion in #30 is a solution for your use case?

If not, can you elaborate on what you're trying to achieve?

**Comment by mahakaal** [comment]
Hello, I needed a quick solution to have a TEX template compiled. I guess your suggestion is more elegant.
I like this bundle, if there is anyway I can help/contribute, please let me know.

Sukhdev.

**Comment by bobvandevijver** [comment]
Great! Then I'll close this PR, but I will make sure to update the documentation for this use-case (maybe I will even include the DirectTwig directly into the source).

If you have any suggestion/use-cases where you need some help, just create a ticket, and then I will see what I can do.

**Pull request closed without merging**
