### PR TITLE
Typo in documentation; join() in table.tex.twig for readability

### PR DESCRIPTION
**Pull request by ednawig**

### CODE REVIEW

**Comment by bobvandevijver** [comment]
Unfortunately, this code will break the latex output when using complex data inside the table, and therefor I can not merge this. 

The `|latex_escape|raw` is missing, which is actually the reason it prints it in this way, as we do not want to put the &-character though that function (as it escapes it). With simple data this would work (strings without special characters for instance), but when the string contains for example ë, it will fail.

**Comment by bobvandevijver** [comment]
The readability might be improved by using the `loop` variables of twig, so I might change that with a future commit.

**Comment by ednawig** [comment]
Yes you are right - sorry . Not sure about the raw though, doesn’t {% autoescape false %} … {% endautoescape %} alleviate the '&' problem?

**Comment by bobvandevijver** [comment]
The problem is not in twig escaping the & character, but the latex_escape filter. Which is needed when you want to use special characters like ë, é ;)

**Pull request closed without merging**
