### PR TITLE
Bibliography support

### PR DESCRIPTION
**Pull request by bobvandevijver**
This should implement support for bibliographies as requested in #39.

### CODE REVIEW

**Comment by bobvandevijver** [comment]
@mario6097 Can you test this? Just use the dev branch from [packagist](https://packagist.org/packages/bobv/latex-bundle#dev-bibliography-support) and configure the `bobv.latex.bibliography_binary.location` to hold you biber executable.

**Review by tobias-93 — APPROVED** [review]
LGTM

**Comment by mario6097** [comment]
Hi
thanks so much. It works fine for my small project.

**Review by mario6097 — APPROVED** [review]
Hi
it works fine for my little project.

**Comment by bobvandevijver** [comment]
Awesome! I will merge this now and release it as [v2.5.0](https://packagist.org/packages/bobv/latex-bundle#v2.5.0)!

**Comment by mario6097** [comment]
Hi
fine, thanks so much. 
I'll comment here if I run into any issue.

**Pull request merged**
